[package]
name = "httprust"
version = "0.1.0"
authors = ["Luis Carlos Navarro Todd <luiscatodd@gmail.com>", "Victoria Sandi Barrantes <vickysandi2406@gmail.com>", "Naomi Ilama Gamboa"]


[dependencies]
rand = "0.7.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"